### ISSUE TITLE
finding MAC Adress form Lego Hub under Windows

### ISSUE THREAD

**Issue by Degeef** [undera/pylgbst#62]
Hi Andrey,

thanks a lot for all the infomation and stuff you published About the Lego Boost interface.

I´ve started today with installing all the Programs and have Problems with my connection to the MoveHub.

I am working with Windows and the Bluegiga hub you recommended.

Follow steps were succesfull:
- pip install -U pylgbst
- pip install pygatt

I am hanging here at the Moment:
"All the functions above have optional arguments to specify adapter name and MoveHub mac address. Please look function source code for details."

in the source Code of  "___init___.py" I have to fill out "Controller" and "hub_mac"
"def get_connection_bluegiga(controller=None, hub_mac=None):"

Where do I find these?

The USB Dongle is connected to the PC, but with pushing the green button on the Hub, Nothing happens.

What am I missing here?

Thanks al lot!!

BR Dennis

**Comment by undera** [comment]
Since those parameters are optional, you don't have to fill those. Only specify those if you really need to.
I suggest you to enable Python logging, to see some more debugging data. Share the command-line output you see.
And also show the code you are trying to run, so we are able to understand what you try.
